Immune/Models/VaccMembers.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;

namespace Immune.Models
{
    public class VaccMembers
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string DOB   { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string City { get; set; }

        public string Dose1 { get; set; }
        public string Dose2 { get; set; }
        [Required]
        public string uId { get; set; }

    }
}

Immune/Controllers/VaccMembersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;
using System.Xml.Linq;
using Immune.Models;
using Microsoft.AspNetCore.Components.Forms;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Immune.Controllers
{
    public class VaccMembersController : Controller
    {
        public readonly IVaccMembersRepository _membersRepository;
        public readonly IUserRepository _userRepository;
        public readonly IVaccineRepository _vaccineRepository;


        public VaccMembersController(IVaccMembersRepository membersRepository, IVaccineRepository vaccineRepository, IUserRepository userRepository)
        {
            _membersRepository = membersRepository;
            _vaccineRepository = vaccineRepository;
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<VaccMembers> vacc = _membersRepository.GetAllMembers();

            return View(vacc);
        }

        public IActionResult AddMembers()
        {
            List<string> city = new List<string>();
            city=_vaccineRepository.City();
            List<SelectListItem> ObjList = new List<SelectListItem>();
            foreach(string cityItem in city)
            {
                SelectListItem Obj = new SelectListItem();
                Obj.Text = cityItem;
                Obj.Value = cityItem;
                ObjList.Add(Obj);
            }
            ViewBag.city = ObjList;

            IEnumerable<Vaccine> vacc = _vaccineRepository.GetAllVaccineDest();
            ViewBag.vacc = vacc;
            return View();
        }
        [HttpPost]
        public IActionResult AddMembers(VaccMembers model)
        {
            if (ModelState.IsValid)
            {
                UserDetails user = _userRepository.GetUserByEmail(model.Email);
                VaccMembers member = _membersRepository.GetUserByEmail(model.Email);
                if (user == null && member==null)
                {
                    VaccMembers vaccMembers = new VaccMembers
                    {
                        Name = model.Name,
                        DOB = model.DOB,
                        Email = model.Email,
                        City = model.City,
                        uId = model.uId,
                    };
                    _membersRepository.Add(vaccMembers);
                    IEnumerable<VaccMembers> vacc = _membersRepository.GetAllMembers();
                    return View("Index",vacc);
                 }
                else
                {
                    ViewBag.msg = "Email already exists";
                    IEnumerable<VaccMembers> vacc1 = _membersRepository.GetAllMembers();
                    return View();
                }
            }

            return View();
        }

        public IActionResult BookSlot(int Id)
        {
            IEnumerable<VaccMembers> members = _membersRepository.GetAllMembers();
            string city = null;
            foreach(VaccMembers member in members)
            {
                if(member.Id == Id)
                {
                    city = member.City;
                }
            }
            List<string> dates = new List<string>();
            IEnumerable<Vaccine> vacc = _vaccineRepository.GetAllVaccineDest();
            List<SelectListItem> ObjList = new List<SelectListItem>();
            foreach (Vaccine vaccine1 in vacc)
            {
                if(vaccine1.city == city)
                {
                    SelectListItem Obj = new SelectListItem();
                    Obj.Text = vaccine1.Date;
                    Obj.Value = vaccine1.Date;
                    ObjList.Add(Obj);
                }
            }
            TempData["city"] = city;
            TempData["uId"] = Id;
            ViewBag.dates = ObjList;
            return View();
        }

        [HttpGet]
        public IActionResult slot(string Date, string dose)
        {
            bool flag=false;
            IEnumerable<Vaccine> vacc = _vaccineRepository.GetAllVaccineDest();
            VaccMembers vaccMembers = null;
            Vaccine vaccine = null;
            foreach (Vaccine vaccine1 in vacc)
            {
                if ((string)TempData["city"]==vaccine1.city && vaccine1.Date == Date)
                {
                    int id = (int)TempData["uId"];
                        
                     vaccMembers = _membersRepository.GetVaccMemberById(id);
                     vaccine = _vaccineRepository.GetRow((string)TempData["city"], Date);
                    int age = 0;
                    age = DateTime.Now.Subtract(Convert.ToDateTime(vaccMembers.DOB)).Days;
                    age = age / 365;
                    if (dose == "dose1")
                    {
                        
                      //  if(int.Parse(vaccine1.Dose1) != 0)
                       // {
                            if (age >= 18)
                            {
                               // int temp = (int.Parse(vaccine1.Dose1) - 1);
                                vaccine.Dose1 = Date;
                                vaccMembers.Dose1 = Date;
                                ViewBag.msg = "Your slot has booked successfully !!";
                                
                            }
                            else
                            {
                                ViewBag.msg = "You can not take this vaccine you are not 18";
                            }
                        //}
                    }
                    else if(dose == "dose2")
                    {
                     //  if (int.Parse(vaccine1.Dose2) != 0)
                       // {
                            if(vaccMembers.Dose1 != null)
                            {
                                DateTime dose1 = Convert.ToDateTime(vaccMembers.Dose1);
                                int diff = dose1.Subtract(Convert.ToDateTime(Date)).Days;
                                if(diff < -60)
                                {
                                //int temp = (int.Parse(vaccine1.Dose2) - 1);
                                vaccine.Dose2 = Date;
                                    vaccMembers.Dose2 = Date;
                                    ViewBag.msg = "Your slot has booked successfully !!";
                                   
                                }
                                else
                                {
                                    ViewBag.msg = "You have not completed 3 months afetr taking the first dose !!!";
                                    
                                }
                            }
                            else
                            {
                                ViewBag.msg = "You have not taken Dose1.So, please take Dose1.";
                               
                            }
                      //  }
                        //else
                        //{
                          //  ViewBag.msg = "Not enough vaccine. Check for other dates";
                            
                        //}
                    }
                    else
                    {
                        ViewBag.msg = "Please type dose1 or dose2 only. It is case sensitive.";
                        
                    }
                    flag = true;
                    break;
                }
            }
            if(flag)
            {

                _membersRepository.Update(vaccMembers);
                _vaccineRepository.Update(vaccine);
                IEnumerable<VaccMembers> vacc1 = _membersRepository.GetAllMembers();
                return View("Index", vacc1);
               
            }
            return View();
        }

        public IActionResult Edit(int Id)
        {
            VaccMembers vacc = _membersRepository.GetVaccMemberById(Id);
            return View(vacc);
        }

        [HttpPost]
        public IActionResult Edit(VaccMembers model)
        {
            if (ModelState.IsValid)
            {
                _membersRepository.Update(model);
                ViewBag.msg = "Details Updated Successfully.";
                IEnumerable<VaccMembers> vacc1 = _membersRepository.GetAllMembers();
                return View("Index", vacc1);
            }
            return View();
        }

        public IActionResult Details(int Id)
        {
            VaccMembers vacc = _membersRepository.GetVaccMemberById(Id);
            return View(vacc);
        }

        public IActionResult ShowCert(int Id)
        {
            var vacc = _membersRepository.GetVaccMemberById(Id);
            if(vacc.Dose1 != null && vacc.Dose2 != null)
            {
                return View(vacc);
            }
            else
            {
                ViewBag.msg = "You have not taken both the doses. So, You can not generate certificate.";
                IEnumerable<VaccMembers> vacc1 = _membersRepository.GetAllMembers();
                return View("Index", vacc1);
            }
        }
        public JsonResult GetDose(string city)
        {
            IEnumerable<Vaccine> vacc= _vaccineRepository.GetAllVaccineDest();
            string dose1 = null, dose2 = null;
            foreach(var item in vacc)
            {
                if (item.city == city)
                {
                    dose1 = item.Dose1;
                    dose2 = item.Dose2;
                }
            }
            List<string> dose = new List<string>();
            dose.Add(dose1);
            dose.Add(dose2);
            return Json(dose);

        }

        
    }
}

Immune/Views/VaccMembers/AddMembers.cshtml
@model Immune.Models.VaccMembers
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "AddMembers";
}

<h1>AddMembers</h1>

<h4>VaccMembers</h4>
<hr />
<p>
    @HttpContextAccessor.HttpContext.Session.GetInt32("UserId")
</p>

<div class="row">
    <div class="col-md-6">
        <form asp-action="AddMembers" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input type="date" asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select class="form-select temp" onchange="bookSlot()" name="City" asp-items="@ViewBag.city">
                    <option value="0" selected>Default</option>
                </select>
            </div>
            
            <div class="form-group">
                <input asp-for="uId" class="form-control" type="hidden" value="@HttpContextAccessor.HttpContext.Session.GetInt32("UserId")" />
                <span asp-validation-for="uId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@if (ViewBag.msg != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.msg");
        };
    </script>
}

Immune/Views/VaccMembers/BookSlot.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Immune.Models.Vaccine

 <div class="col-md-6">
        <form asp-action="slot" method="get">
           
           <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
            <select asp-for="Date" id="date" onchange="getSlot()" class="form-select temp" name="Date" asp-items="@(new SelectList(@ViewBag.dates,"Value","Text" ))">
                    <option value="0" selected>Default</option>
             </select>
            </div>
        <div>
            <input type="text" name="dose" value="dose1" />
        </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>

        </div>

<script>
    function getSlot(){
        var date = document.getElementById('date')
    }
</script>

Immune/Views/VaccMembers/Details.cshtml
@model Immune.Models.VaccMembers

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VaccMembers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dose1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dose1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dose2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dose2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.uId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.uId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Immune/Views/VaccMembers/Edit.cshtml
@model Immune.Models.VaccMembers

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>VaccMembers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="uId" class="control-label"></label>
                <input type="hidden" asp-for="uId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@if (ViewBag.msg != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.msg");
        };
    </script>
}

Immune/Views/VaccMembers/Index.cshtml
@model IEnumerable<Immune.Models.VaccMembers>

@{
    ViewData["Title"] = "Index";
}
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<h1>List Of Members that you have book the slots</h1>

<div class="text-center">
    <a class="text-light btn btn-primary font-weight-bold" asp-action="AddMembers" asp-controller="VaccMembers">Add Members</a>
</div>

<p>
    @HttpContextAccessor.HttpContext.Session.GetInt32("UserId")
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dose1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dose2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.uId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.uId == @HttpContextAccessor.HttpContext.Session.GetInt32("UserId").ToString())
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DOB)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dose1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dose2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.uId)
                    </td>
                    <td>
                        <a asp-action="BookSlot" asp-route-id="@item.Id" class="btn btn-warning">Book Slot</a>
                    </td>
                    <td>
                        <a asp-action="ShowCert" asp-route-id="@item.Id" class="btn btn-warning">Show Certificate</a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                    </td>
                </tr>
            }
            
        }
    </tbody>
</table>

@if (ViewBag.msg != null)
{
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.msg");
            };
        </script>
}

Immune/Views/VaccMembers/ShowCert.cshtml
@model Immune.Models.VaccMembers

@{
    ViewData["Title"] = "ShowCert";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="c:\users\diya\source\repos\immune\immune\wwwroot\lib\bootstrap\css\bootstrap.css" rel="stylesheet" />
<link href="c:\users\diya\source\repos\immune\immune\wwwroot\lib\bootstrap\css\bootstrap.min.css" rel="stylesheet" />
<link href="c:\users\diya\source\repos\immune\immune\wwwroot\lib\bootstrap\css\bootstrap.rtl.css" rel="stylesheet" />
<link href="c:\users\diya\source\repos\immune\immune\wwwroot\lib\bootstrap\css\bootstrap.rtl.min.css" rel="stylesheet" />
 <title>Document</title>
 <style>
     .outer-border{
    width:800px; height:650px; padding:20px; text-align:center; border: 10px solid #673AB7;    margin-left: 21%;
}

.inner-dotted-border{
    width:750px; height:600px; padding:20px; text-align:center; border: 5px solid #673AB7;border-style: dotted;
}

.certification{
    font-size:50px; font-weight:bold;    color: #663ab7;
}

.certify{
    font-size:25px;
}

.name{
    font-size:30px;    color: green;
}

.fs-30{
    font-size:30px;
}

.fs-20{
    font-size:20px;
}
 </style>
</head>
<body>
    
    <div class="outer-border">
<div class="inner-dotted-border">
       <span class="certification">Certificate of Completion</span>
       <br><br>
       <span class="certify"><i>This is to certify that</i></span>
       <br><br>
            <span class="name"><b>@Html.DisplayFor(model => model.Name)</b></span><br /><br />
       <span class="certify"><i>has successfully completed both the doses.</i></span> <br/><br/>
            <p class="fs-20">Email: <span class="fs-20"><b> @Html.DisplayFor(model => model.Email)</b> </span> <br /> </p>
            <p class="fs-20">DOB: <span class="fs-20"><b> @Html.DisplayFor(model => model.DOB)</b> </span> <br /> </p>
            <p class="fs-20">City: <span class="fs-20"> <b>@Html.DisplayFor(model => model.City)</b> </span> <br /> </p>
            
            
            </div>

</div>
</div>



    <div>
        <td>
            <a asp-action="ShowCert" onclick="window.print()" class="btn btn-warning">Download</a>
        </td>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
   
</body>
</html>

Immune/Views/VaccMembers/slot.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Slot page</h1>