Immune/Models/Vaccine.cs
using System.ComponentModel.DataAnnotations;

namespace Immune.Models
{
    public class Vaccine
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string city { get; set; }
        [Required]
        public string Dose1 { get; set; }
        [Required]
        public string Dose2 { get; set; }
        [Required]
        public string Date { get; set; }
    }
}

Immune/Controllers/VaccineController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Immune.Models;

namespace Immune.Controllers
{
    public class VaccineController : Controller
    {
        private readonly IVaccineRepository _vaccRepository;

        public VaccineController(IVaccineRepository vaccRepository)
        {
            _vaccRepository = vaccRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<Vaccine> vacc = _vaccRepository.GetAllVaccineDest();

            return View(vacc);
        }

        public IActionResult AddCenter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCenter(Vaccine model)
        {
            if (ModelState.IsValid)
            {

                
                    Vaccine vacc = new Vaccine
                    {
                        city = model.city,
                        Dose1 = model.Dose1,
                        Dose2 = model.Dose2,
                        Date = model.Date,
                    };
                    _vaccRepository.Add(vacc);
                    IEnumerable<Vaccine> vac = _vaccRepository.GetAllVaccineDest();
                    return RedirectToAction("Index", vac);

                
                
            }
            return View();
        }

        
    }
}

Immune/Views/Vaccine/AddCenter.cshtml
@model Immune.Models.Vaccine

@{
    ViewData["Title"] = "AddCenter";
}

<h1>AddCenter</h1>

<h4>Vaccine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCenter" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="city" class="control-label"></label>
                <input asp-for="city" class="form-control" />
                <span asp-validation-for="city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dose1" class="control-label"></label>
                <input asp-for="Dose1" class="form-control" />
                <span asp-validation-for="Dose1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dose2" class="control-label"></label>
                <input asp-for="Dose2" class="form-control" />
                <span asp-validation-for="Dose2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input type="date" asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Immune/Views/Vaccine/Index.cshtml
@model IEnumerable<Immune.Models.Vaccine>

@{
    ViewData["Title"] = "Index";
}

<h1>City and No. of vaccine</h1>

<div class="text-center">
    <a class="text-light btn btn-primary font-weight-bold" asp-action="AddCenter" asp-controller="Vaccine">Add Center</a>
</div>


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Dose1)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Dose2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dose1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dose2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>